branch-defaults:
  master:
    environment: Dockerreact-env
global:
  application_name: docker-react
  default_ec2_keyname: e-skdnywd222
  default_platform: Docker running on 64bit Amazon Linux 2/3.5.5
  default_region: ap-southeast-1
  sc: git