version: 2.1

jobs:
  build-test-deploy:
    working_directory: /app
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker build -t yudhapradiptar/docker-react -f Dockerfile.dev .
      - run:
          name: test
          command: docker run -e CI=true yudhapradiptar/docker-react npm test
      - run:
          name: deploy
          command: eb deploy Dockerreact-env

workflows:
  deploy-workflow:
    jobs:
    - build-test-deploy:
        filters:
          branches:
            only:
              - master
