version: 2.1

jobs:
  build-test-deploy:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker build -t yudhapradiptar/docker-react -f Dockerfile.dev .
      - run:
          name: test
          command: docker run -e CI=true yudhapradiptar/docker-react npm test
      - run:
          name: install awsebcli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      - run:
          name: deploy
          command: eb deploy Dockerreact-env

workflows:
  build:
    jobs:
    - build-test-deploy:
        filters:
          branches:
            only:
              - master
