version: 2.1

jobs:
  build-test:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker build -t yudhapradiptar/docker-react -f Dockerfile.dev .
      - run:
          name: test
          command: docker run -e CI=true yudhapradiptar/docker-react npm test
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      - run:
          name: deploy
          command: eb deploy Dockerreact-env
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - run:
          name: deploy
          command: eb deploy Dockerreact-env
          requires:
            - build-test

workflows:
  deploy-workflow:
    jobs:
      - build-test
      - deploy:
          filters:
            branches:
              only:
                - master
